// vue-bookstore/src/components/BookList.vue
<template>
  <div class="book-list">
    <Book v-for="book in books" v-bind:key="book.id" v-bind:book="book"></Book>
  </div>
</template>

<script>
import { BookService } from "../services/books.service.js";
import Book from "./Book";

export default {
  name: "BookList",
  components: {
    Book,
  },
  data() {
    return {
      books: [],
    };
  },
  mounted() {
    console.log("Fetching books...");
    BookService.getBooks().then((data) => {
      this.books = data;
    });
  },
};
</script>

<style lang="scss">
.book-list {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  column-gap: 20px;
  row-gap: 20px;
  margin-top: 20px;
}
</style>

// react-bookstore/src/components/Books/BookList.jsx
import React, { useState, useEffect } from "react";
import { getBooks } from "../../services/books.service";
import { Book } from "./Book";
import "./BookList.scss";

export const BookList = (props) => {
  const [books, setBooks] = useState([]);

  useEffect(() => {
    getBooks()
      .then((data) => {
        setBooks(data);
      })
      .catch((err) => {
        console.error(err);
        setBooks([]);
      });
  }, []);

  return (
    <div data-testid="booklist" className="book-list">
      {books.map((b) => (
        <Book key={`book-${b.title.replace(" ", "_")}`} book={b} />
      ))}
    </div>
  );
};
