// vue-bookstore/src/components/AddAuthor.vue
<template>
  <div>
    <h1>{{ $t("admin.addAuthor.title") }}</h1>
    <div class="message">
      <div v-if="message" class="success">{{ message }}</div>
      <div v-if="error" class="error">{{ error }}</div>
      <div v-if="formErrors.length" class="error">
        {{ $t("forms.errorList") }}
        <ul>
          <li v-for="(e, i) in formErrors" :key="i">{{ e }}</li>
        </ul>
      </div>
    </div>
    <form @submit.prevent="submitNewAuthor">
      <div class="control">
        <label for="name">{{
          $t("admin.addAuthor.form.controls.name.label")
        }}</label>
        <input type="text" name="name" id="name" v-model="name" />
      </div>
      <div>
        <input type="submit" :value="$t('admin.addAuthor.form.buttons.add')" />
      </div>
    </form>
  </div>
</template>

<script>
import { AuthorsService } from "../services/authors.service.js";

export default {
  name: "AddAuthor",
  data() {
    return {
      name: "",
      error: null,
      message: null,
      formErrors: [],
    };
  },
  methods: {
    submitNewAuthor() {
      if (this.validateForm()) {
        AuthorsService.addAuthor({
          name: this.name,
        })
          .then(() => {
            this.message = this.$t("admin.addAuthor.messages.addAuthorSuccess");
            this.resetForm();
          })
          .catch((err) => (this.error = err));
      }
    },
    validateForm() {
      let formIsValid = true;
      this.formErrors = [];

      if (!this.name) {
        this.formErrors.push(
          this.$t("admin.addAuthor.form.controls.name.required")
        );
        formIsValid = false;
      }

      return formIsValid;
    },
    resetForm() {
      this.name = "";
    },
  },
};
</script>

<style lang="scss"></style>

// react-bookstore/src/components/Admin/AddAuthor.jsx
import React, { useState, useRef } from "react";
import { addAuthor } from "../../services/author.service";
import { useTranslation } from "react-i18next";

export const AddAuthor = (props) => {
  const name = useRef(null);

  const [message, setMessage] = useState();
  const [errorMessage, setErrorMessage] = useState();

  const { t } = useTranslation();

  const handleSubmit = (e) => {
    e.preventDefault();
    addAuthor({
      name: name.current.value,
    })
      .then((data) => {
        name.current.value = "";
        setMessage("admin.addAuthor.messages.addAuthorSuccess");
        setErrorMessage(null);
      })
      .catch((err) => setErrorMessage(err.message));
  };

  return (
    <div data-testid="admin-add-author">
      <h1>{t("admin.addAuthor.title")}</h1>
      <div className="message">
        {message && !errorMessage && <div className="success">{t(message)}</div>}
        {errorMessage && <div className="error">{errorMessage}</div>}
      </div>
      <form onSubmit={handleSubmit}>
        <div data-testid="name" className="control">
          <label htmlFor="name">{t("admin.addBook.form.controls.title.label")}</label>
          <input type="text" name="name" id="name" ref={name} defaultValue="" />
        </div>
        <div>
          <input type="submit" value={t("admin.addBook.form.buttons.add")} />
        </div>
      </form>
    </div>
  );
};
