// react-bookstore/src/components/SwitchLang.jsx
import React from "react";
import { useTranslation } from "react-i18next";

export const SwitchLang = (props) => {
  const { i18n } = useTranslation();

  const switchLang = () => {
    if (i18n.language === "en") {
      i18n.changeLanguage("fr");
    } else {
      i18n.changeLanguage("en");
    }
  };

  return <button onClick={switchLang}>{i18n.language.toUpperCase()}</button>;
};

// vue-bookstore/src/components/SwitchLang.vue
<template>
  <button @click="switchLang">{{ $i18n.locale | uppercase }}</button>
</template>

<script>
export default {
  name: "SwitchLang",
  methods: {
    switchLang() {
      if (this.$i18n.locale === "en") {
        this.$i18n.locale = "fr";
      } else {
        this.$i18n.locale = "en";
      }
    },
  },
  filters: {
    uppercase(value) {
      if (!value) return "";
      return value.toUpperCase();
    },
  },
};
</script>

<style lang="scss"></style>
